"""Estilos centralizados por tipo de componente."""

LABELS = {
    'configuracion_titulo_menu': 'color: #888888;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_cambiar_valores': 'color: #888888;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_usuarios_agregados': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_hora': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_dia': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_mes': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_validar': 'color: #888888;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_contraseña_acceso': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_generico': 'color: #888888;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_pc_agregados': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_pc_actual': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_id': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_descripcion': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_cambiar_pc': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_suscripcion': 'color: #888888;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_codigo': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_estado_actual': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'configuracion_titulo_dias_restantes_suscripción': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'creditos_titulo_casilleros': 'color: #888888;font-size: 30px; font-weight: bold;',
    'creditos_titulo_principal': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'creditos_titulo_nombre1': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'creditos_titulo_nombre2': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'creditos_titulo_carrera': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'creditos_titulo_universidad': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'creditos_titulo_contacto': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'creditos_titulo_numero1': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'creditos_titulo_numero2': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'principal_menu_label': 'color: #888888; font-size: 20px; font-weight: bold;',
    'registros_titulo_menu': 'color: #888888;font-size: 30px; font-weight: bold;',
    'registros_titulo_registros': 'color: #888888;font-size: 30px; font-weight: bold;',
    'registros_titulo_fijo': 'color: #888888;font-size: 30px; font-weight: bold;',
    'registros_titulo_mensualidades': 'color: #888888;font-size: 30px; font-weight: bold;',
    'registros_titulo_resumen': 'color: #888888;font-size: 30px; font-weight: bold;',
    'registros_label_fecha': 'color: #FFFFFF; font-size: 20px; font-weight: bold;',
    'registros_label_hora': 'color: #FFFFFF; font-size: 20px; font-weight: bold;',
    'registros_label_registros_dia': 'color: #FFFFFF; font-size: 18px;',
    'registros_label_total_dia': 'color: #00FF00; font-size: 18px; font-weight: bold;',
    'registros_label_registros_hora': 'color: #FFFFFF; font-size: 18px;',
    'registros_label_total_hora': 'color: #00FF00; font-size: 18px; font-weight: bold;',
    'registros_label_registros_mes': 'color: #FFFFFF; font-size: 18px;',
    'registros_label_total_mes': 'color: #00FF00; font-size: 18px; font-weight: bold;',
    'registros_label_registros_fijos': 'color: #FFFFFF; font-size: 18px;',
    'registros_label_total_fijos': 'color: #00FF00; font-size: 18px; font-weight: bold;',
    'registros_label_total_registros': 'color: #00BFFF; font-size: 22px; font-weight: bold;',
    'registros_label_total_general': 'color: #FFD700; font-size: 24px; font-weight: bold;',
    'reportes_titulo_casilleros': 'color: #888888;font-size: 30px; font-weight: bold;',
    'reportes_titulo_tabla_reportes': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'reportes_label_desde': 'color: #FFFFFF;font-size: 30px;',
    'reportes_label_hasta': 'color: #FFFFFF;font-size: 30px;',
    'tickets_titulo_menu': 'color: #888888;font-size: 30px; font-weight: bold;',
    'tickets_titulo_tickets': 'color: #888888;font-size: 25px; font-weight: bold;',
    'tickets_label_placa': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_cascos': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_tiempo': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_casillero': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_casilleros_dis': 'color: #FFFFFF;font-size: 30px;',
    'tickets_titulo_tickets_2': 'color: #888888;font-size: 30px; font-weight: bold;',
    'tickets_label_codigo': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_placa_2': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_casillero_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_cascos_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_f_ingreso': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_h_ingreso': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_f_salida': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_h_salida': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_pagado_por': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_tiempo_total': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_total_a_pagar': 'color: #FFFFFF;font-size: 30px;',
    'tickets_titulo_tickets_3': 'color: #888888;font-size: 30px; font-weight: bold;',
    'tickets_label_codigo_2': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_tipo': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_nota': 'color: #FFFFFF;font-size: 40px;',
    'tickets_label_valor': 'color: #FFFFFF;font-size: 40px;',
    'tickets_titulo_tickets_4': 'color: #888888;font-size: 30px; font-weight: bold;',
    'tickets_label_codigo_3': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_tipo_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_nota_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_f_ingreso_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_h_ingreso_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_f_salida_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_h_salida_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_tiempo_total_2': 'color: #FFFFFF;font-size: 30px;',
    'tickets_label_total_apagar': 'color: #FFFFFF;font-size: 30px;',
    'tickets_titulo_tickets_5': 'color: #888888;font-size: 30px; font-weight: bold;',
    'tickets_titulo_placa': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_nombre': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_telefono': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_mensualidades_vigentes': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_tickets_6': 'color: #888888;font-size: 30px; font-weight: bold;',
    'tickets_titulo_codigo': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_placa_2': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_nombre_2': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_fecha_ingreso': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_fecha_u_pago': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_fecha_renovacion': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_telefono_2': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_hora_ingreso': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_hora_u_pago': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'tickets_titulo_total_a_pagar': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'casilleros_titulo_casilleros': 'color: #888888;font-size: 30px; font-weight: bold;',
    'casilleros_titulo_tablacasilleros': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'casilleros_titulo_agregar_casillero': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'casilleros_titulo_numero': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'casilleros_titulo_pc': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'casilleros_titulo_estado': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'casilleros_titulo_cambiar_pc': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'casilleros_titulo_pc_cambiar': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'casilleros_titulo_tabla_orden_de_llegada': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
}

LINEAS = {
    'configuracion_linea_vertical': 'color: #FFFFFF;',
    'configuracion_linea_horizontal2': 'color: #FFFFFF;',
    'configuracion_linea_horizontal1': 'color: #FFFFFF;',
    'configuracion_linea_horizontal1_2': 'color: #FFFFFF;',
    'configuracion_linea_horizontal1_3': 'color: #FFFFFF;',
    'configuracion_linea_horizontal1_4': 'color: #FFFFFF;',
    'creditos_linea_horizontal1': 'color: #FFFFFF;',
    'principal_line_frame2': 'color: #222126;',
    'registros_linea_vertical': 'color: #FFFFFF;',
    'registros_linea_horizontal2': 'color: #FFFFFF;',
    'registros_linea_horizontal1': 'color: #FFFFFF;',
    'registros_linea_horizontal1_2': 'color: #FFFFFF;',
    'registros_linea_horizontal1_3': 'color: #FFFFFF;',
    'registros_linea_horizontal1_4': 'color: #FFFFFF;',
    'registros_linea_horizontal2_2': 'color: #FFFFFF;',
    'reportes_linea_horizontal1': 'color: #FFFFFF;',
    'tickets_linea_vertical': 'color: #FFFFFF;',
    'tickets_linea_horizontal2': 'color: #FFFFFF;',
    'tickets_linea_horizontal1': 'color: #FFFFFF;',
    'tickets_linea_horizontal1_2': 'color: #FFFFFF;',
    'tickets_linea_horizontal1_3': 'color: #FFFFFF;',
    'tickets_linea_horizontal1_4': 'color: #FFFFFF;',
    'tickets_linea_horizontal1_5': 'color: #FFFFFF;',
    'tickets_linea_horizontal1_6': 'color: #FFFFFF;',
    'casilleros_linea_horizontal1': 'color: #FFFFFF;',
}

BOTONES = {
    'configuracion_boton_usuarios': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_pc': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_suscripcion': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_aceptar': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_ocultar_contrasena': 'color: White; background-color: #151419; font-size: 30px; border-radius: 1px; padding: 10px 10px;',
    'configuracion_boton_validar': 'color: White; background-color: #222125; font-size: 35px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_editar': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_eliminar': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_guardar': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_cambiar': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 20px;',
    'configuracion_boton_validar_2': 'color: White; background-color: #222125; font-size: 35px; border-radius: 15px; padding: 10px 20px;',
    'principal_boton_registros': 'background-color: #222125; color: White; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'principal_botontickets': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'principal_boton_gestionar_casilleros': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'principal_boton_reportes': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'principal_boton_configuracion': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'principal_boton_con_creditos': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'principal_boton_configuracion_2': 'background-color: #222125; color: White; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'principal_boton_registros_2': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'principal_ultimo_boton_seleccionado': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'registros_boton_registros': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'registros_boton_fijos': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'registros_boton_mensualidades': 'color: White; background-color: #222125; font-size: 10px; border-radius: 15px; padding: 10px 20px;',
    'registros_boton_resumen': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'registros_boton_buscar': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px',
    'registros_boton_reimprimir_registro': 'color: White; background-color: #222125;  border-radius: 15px; padding: 10px;',
    'registros_boton_eliminar_registro': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_guardar_edicion': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_limpiar_registro': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_buscar_2': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_reimprimir_registro_2': 'color: White; background-color: #222125;border-radius: 15px; padding: 10px;',
    'registros_boton_eliminar_registro_2': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_guardar_edicion_2': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_limpiar': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_buscar_3': 'color: White; background-color: #222125;border-radius: 15px; padding: 10px;',
    'registros_boton_reimprimir_registro_3': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_guardar_edicion_3': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_eliminar': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'registros_boton_actualizar_resumen': 'color: White; background-color: #222125; border-radius: 15px; padding: 15px; font-size: 16px;',
    'reportes_boton_reimprimir': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 15px 30px;',
    'reportes_boton_imprimir': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 15px 30px;',
    'reportes_boton_resumen': 'color: White; background-color: #222125; font-size: 20px; border-radius: 15px; padding: 15px 30px;',
    'tickets_boton_ingresar_m': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_sacar_m': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_ingresar_f': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_sacar_f': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_ingresar_mensualidad': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 10px;',
    'tickets_boton_sacar_mensualidad': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 10px;',
    'tickets_boton_cambiarcasillero': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 15px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n            QPushButton:disabled {\n                background-color: #3a3a3a;\n                color: #666666;\n            }\n        ',
    'tickets_boton_imprimir_registro_moto': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_buscar': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_facturar': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_imprimir': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_buscar_fijos': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_botonfacturar_fijos': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'tickets_boton_imprimir_2': 'color: White; background-color: #222125; font-size: 35px; border-radius: 15px; padding: 10px 20px;',
    'tickets_boton_buscar_renovar_mensualidad': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'tickets_boton_renovar_mensualidad': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 20px;',
    'casilleros_boton_agregar': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'casilleros_boton_desocupar': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'casilleros_boton_eliminar': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'casilleros_boton_guardar_pc': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'casilleros_boton_subir': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'casilleros_boton_bajar': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
}

INPUTS = {
    'configuracion_textbox_hora_facturacion': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_dia_fecturacion': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_mes_facturacion': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_contraseña_acceso': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_pc_actual': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_id': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_descripcion': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_codigo': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_estado_actual_suscripcion': 'color: #89d631 ; margin: 0; padding: 0; font-size: 30px;',
    'configuracion_textbox_dias_restantes_suscripcion': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'registros_textbox_filtro_registro_moto': 'color: #FFFFFF;font-size: 30px;',
    'registros_textbox_filtro_registro_fijo': 'color: #FFFFFF;font-size: 30px;',
    'registros_textbox_filtrar_registros_mensualidad': 'color: #FFFFFF; font-size: 30px;',
    'tickets_textbox_placa': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_casillero': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_casilleros_dis': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_codigo_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_placa_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_casillero_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_cascos_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_f_ingreso_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_h_ingreso_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_f_salida_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_h_salida_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_pagado_por_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_tiempo_total_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_total_a_pagar_sacar_moto': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_codigo_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_nota': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_valor': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_codigo_fijo': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_tipo_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_nota_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_f_ingreso_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_h_ingreso_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_f_salida_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_h_salida_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_tiempo_total_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_total_apagar_fijos': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_placa_2': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_nombre': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_telefono': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_mensualidades_vigentes': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_codigo_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_placa_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_nombre_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_fecha_ingreso_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_fecha_u_pago_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_fecha_renovacion_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_telefono_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_hora_ingreso_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_hora_u_pago_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'tickets_textbox_total_a_pagar_renovar_mensualidad': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'casilleros_textbox_numero': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
}

COMBOBOX = {
    'configuracion_combobox_pc': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 30px;',
    'registros_combobox_filtro_registro_moto': 'color: #FFFFFF;font-size: 30px;',
    'registros_combobox_filtro_registro_fijos': 'color: #FFFFFF;font-size: 30px;',
    'registros_combobox_filtrar_registros_mensualidad': 'color: #FFFFFF; font-size: 30px;',
    'tickets_combobox_cascos': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 40px;',
    'tickets_combobox_tiempo': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 40px;',
    'tickets_combobox_tipo': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 40px;',
    'casilleros_combobox_pc_registro': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 20px;',
    'casilleros_combobox_estado': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 20px;',
    'casilleros_combobox_pc_cambiar': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 20px;',
}

TABLAS = {
    'configuracion_tabla_pc_agregados': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'registros_tabla_registros_motos': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'registros_tabla_registros_fijos': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'registros_tabla_mensualidades': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'reportes_tabla_registros': '\n                  QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n                ',
    'casilleros_tabla_registros_casillero': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'casilleros_tabla_orden_de_llenado': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
}

CHECKBOXES = {
    'tickets_checkbox_opcion': 'color: #FFFFFF; font-size: 20px;',
}

CALENDARIOS = {
    'reportes_calendar_desde_widget': 'font-size: 30px;',
    'reportes_calendar_desde_widget_2': 'background-color: #222126; color: white; font-size: 30px; alternate-background-color: #131216;',
    'reportes_calendarhasta_widget': 'font-size: 30px;',
    'reportes_calendarhasta_widget_2': 'background-color: #222126; color: white; font-size: 30px; alternate-background-color: #131216;',
}

OTROS = {
    'principal_ventana': 'background-color: #151419;',
    'principal_sender': 'background-color: #222125; color: white; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'reportes_date_desde': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'reportes_date_hasta': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
}
