STYLES = {
    'pagina_configuracion.py:122': 'color: #FFFFFF;',
    'pagina_configuracion.py:127': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:133': 'color: #FFFFFF;',
    'pagina_configuracion.py:146': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:153': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:160': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:189': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:195': 'color: #FFFFFF;',
    'pagina_configuracion.py:199': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:204': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:208': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:213': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:217': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:222': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:226': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:231': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:267': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:273': 'color: #FFFFFF;',
    'pagina_configuracion.py:277': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:282': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:288': 'color: White; background-color: #151419; font-size: 30px; border-radius: 1px; padding: 10px 10px;',
    'pagina_configuracion.py:298': 'color: White; background-color: #222125; font-size: 35px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:353': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:359': 'color: #FFFFFF;',
    'pagina_configuracion.py:363': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:370': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'pagina_configuracion.py:425': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:445': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:464': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:467': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:475': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:478': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:483': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:487': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:491': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:507': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:511': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 30px;',
    'pagina_configuracion.py:515': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:591': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:597': 'color: #FFFFFF;',
    'pagina_configuracion.py:601': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:605': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:609': 'color: White; background-color: #222125; font-size: 35px; border-radius: 15px; padding: 10px 20px;',
    'pagina_configuracion.py:621': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:625': 'color: #89d631 ; margin: 0; padding: 0; font-size: 30px;',
    'pagina_configuracion.py:631': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_configuracion.py:635': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_creditos.py:22': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_creditos.py:29': 'color: #FFFFFF;',
    'pagina_creditos.py:33': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'pagina_creditos.py:37': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'pagina_creditos.py:41': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'pagina_creditos.py:45': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'pagina_creditos.py:49': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'pagina_creditos.py:53': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'pagina_creditos.py:57': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'pagina_creditos.py:61': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'main.py:24': 'background-color: #151419;',
    'main.py:73': 'color: #888888; font-size: 20px; font-weight: bold;',
    'main.py:79': 'color: #222126;',
    'main.py:83': 'background-color: #222125; color: White; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:90': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:97': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:104': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:111': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:118': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:187': 'background-color: #222125; color: white; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:155': 'background-color: #222125; color: White; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:156': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'main.py:191': 'background-color: #151419; color: #737074; border: none; border-radius: 15px;font-size: 12px;text-align: left;padding-left: 10px;font-weight: bold;min-height: 60px;min-width: 200px;',
    'pagina_registros.py:210': 'color: #FFFFFF;',
    'pagina_registros.py:215': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_registros.py:221': 'color: #FFFFFF;',
    'pagina_registros.py:226': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'pagina_registros.py:234': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'pagina_registros.py:241': 'color: White; background-color: #222125; font-size: 10px; border-radius: 15px; padding: 10px 20px;',
    'pagina_registros.py:248': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'pagina_registros.py:289': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_registros.py:295': 'color: #FFFFFF;',
    'pagina_registros.py:303': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'pagina_registros.py:355': 'color: #FFFFFF;font-size: 30px;',
    'pagina_registros.py:359': 'color: #FFFFFF;font-size: 30px;',
    'pagina_registros.py:365': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px',
    'pagina_registros.py:372': 'color: White; background-color: #222125;  border-radius: 15px; padding: 10px;',
    'pagina_registros.py:385': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:395': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:416': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:438': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_registros.py:444': 'color: #FFFFFF;',
    'pagina_registros.py:452': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'pagina_registros.py:506': 'color: #FFFFFF;font-size: 30px;',
    'pagina_registros.py:512': 'color: #FFFFFF;font-size: 30px;',
    'pagina_registros.py:517': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:525': 'color: White; background-color: #222125;border-radius: 15px; padding: 10px;',
    'pagina_registros.py:539': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:549': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:569': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:591': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_registros.py:597': 'color: #FFFFFF;',
    'pagina_registros.py:605': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'pagina_registros.py:658': 'color: #FFFFFF; font-size: 30px;',
    'pagina_registros.py:662': 'color: #FFFFFF; font-size: 30px;',
    'pagina_registros.py:669': 'color: White; background-color: #222125;border-radius: 15px; padding: 10px;',
    'pagina_registros.py:677': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:689': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:713': 'color: White; background-color: #222125; border-radius: 15px; padding: 10px;',
    'pagina_registros.py:742': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_registros.py:749': 'color: #FFFFFF;',
    'pagina_registros.py:755': 'color: #FFFFFF; font-size: 20px; font-weight: bold;',
    'pagina_registros.py:759': 'color: #FFFFFF; font-size: 20px; font-weight: bold;',
    'pagina_registros.py:764': 'color: #FFFFFF; font-size: 18px;',
    'pagina_registros.py:768': 'color: #00FF00; font-size: 18px; font-weight: bold;',
    'pagina_registros.py:773': 'color: #FFFFFF; font-size: 18px;',
    'pagina_registros.py:777': 'color: #00FF00; font-size: 18px; font-weight: bold;',
    'pagina_registros.py:782': 'color: #FFFFFF; font-size: 18px;',
    'pagina_registros.py:786': 'color: #00FF00; font-size: 18px; font-weight: bold;',
    'pagina_registros.py:791': 'color: #FFFFFF; font-size: 18px;',
    'pagina_registros.py:795': 'color: #00FF00; font-size: 18px; font-weight: bold;',
    'pagina_registros.py:802': 'color: #FFFFFF;',
    'pagina_registros.py:807': 'color: #00BFFF; font-size: 22px; font-weight: bold;',
    'pagina_registros.py:812': 'color: #FFD700; font-size: 24px; font-weight: bold;',
    'pagina_registros.py:817': 'color: White; background-color: #222125; border-radius: 15px; padding: 15px; font-size: 16px;',
    'pagina_Reportes.py:94': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_Reportes.py:101': 'color: #FFFFFF;',
    'pagina_Reportes.py:105': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'pagina_Reportes.py:113': '\n                  QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n                ',
    'pagina_Reportes.py:172': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 15px 30px;',
    'pagina_Reportes.py:199': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Reportes.py:203': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Reportes.py:210': 'font-size: 30px;',
    'pagina_Reportes.py:211': 'background-color: #222126; color: white; font-size: 30px; alternate-background-color: #131216;',
    'pagina_Reportes.py:217': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Reportes.py:221': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Reportes.py:229': 'font-size: 30px;',
    'pagina_Reportes.py:230': 'background-color: #222126; color: white; font-size: 30px; alternate-background-color: #131216;',
    'pagina_Reportes.py:237': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 15px 30px;',
    'pagina_Reportes.py:256': 'color: White; background-color: #222125; font-size: 20px; border-radius: 15px; padding: 15px 30px;',
    'pagina_Tickets.py:203': 'color: #FFFFFF;',
    'pagina_Tickets.py:207': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:212': 'color: #FFFFFF;',
    'pagina_Tickets.py:217': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:239': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:261': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:282': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:303': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 10px;',
    'pagina_Tickets.py:311': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 10px;',
    'pagina_Tickets.py:351': 'color: #888888;font-size: 25px; font-weight: bold;',
    'pagina_Tickets.py:358': 'color: #FFFFFF;',
    'pagina_Tickets.py:363': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:367': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:373': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:378': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 40px;',
    'pagina_Tickets.py:389': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:394': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 40px;',
    'pagina_Tickets.py:399': 'color: #FFFFFF; font-size: 20px;',
    'pagina_Tickets.py:404': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:407': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:415': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 15px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n            QPushButton:disabled {\n                background-color: #3a3a3a;\n                color: #666666;\n            }\n        ',
    'pagina_Tickets.py:443': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:447': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:454': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:526': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:533': 'color: #FFFFFF;',
    'pagina_Tickets.py:538': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:542': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:548': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:552': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:558': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:581': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:585': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:590': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:594': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:600': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:604': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:609': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:613': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:619': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:623': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:628': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:632': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:638': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:642': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:647': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:651': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:657': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:661': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:666': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:754': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:761': 'color: #FFFFFF;',
    'pagina_Tickets.py:766': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:770': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:777': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:782': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 40px;',
    'pagina_Tickets.py:787': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:791': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:796': 'color: #FFFFFF;font-size: 40px;',
    'pagina_Tickets.py:800': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:806': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:860': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:867': 'color: #FFFFFF;',
    'pagina_Tickets.py:872': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:876': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:881': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:903': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:907': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:912': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:916': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:922': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:926': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:931': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:935': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:941': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:945': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:950': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:954': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:960': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:964': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:969': 'color: #FFFFFF;font-size: 30px;',
    'pagina_Tickets.py:973': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:978': '\n            QPushButton {\n                color: white; \n                background-color: #222125; \n                font-size: 30px; \n                border-radius: 15px; \n                padding: 15px 30px;\n            }\n            QPushButton:pressed {\n                background-color: #444444;\n                color: lightgray;\n                border: 2px solid #555555;\n            }\n        ',
    'pagina_Tickets.py:1050': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1057': 'color: #FFFFFF;',
    'pagina_Tickets.py:1062': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1066': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1072': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1076': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1081': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1085': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1090': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1094': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1101': 'color: White; background-color: #222125; font-size: 35px; border-radius: 15px; padding: 10px 20px;',
    'pagina_Tickets.py:1143': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1150': 'color: #FFFFFF;',
    'pagina_Tickets.py:1155': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1159': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1163': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1167': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1172': 'color: White; background-color: #222125; font-size: 25px; border-radius: 15px; padding: 10px 20px;',
    'pagina_Tickets.py:1179': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1183': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1191': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1195': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1202': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1206': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1213': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1217': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1223': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1227': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1234': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1238': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1245': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1249': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1255': 'color: #FFFFFF;font-size: 30px; font-weight: bold;',
    'pagina_Tickets.py:1259': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Tickets.py:1265': 'color: White; background-color: #222125; font-size: 30px; border-radius: 15px; padding: 10px 20px;',
    'pagina_Casilleros.py:96': 'color: #888888;font-size: 30px; font-weight: bold;',
    'pagina_Casilleros.py:103': 'color: #FFFFFF;',
    'pagina_Casilleros.py:107': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'pagina_Casilleros.py:111': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'pagina_Casilleros.py:115': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'pagina_Casilleros.py:119': 'color: #FFFFFF; margin: 0; padding: 0; font-size: 30px;',
    'pagina_Casilleros.py:124': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'pagina_Casilleros.py:128': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 20px;',
    'pagina_Casilleros.py:132': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'pagina_Casilleros.py:137': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 20px;',
    'pagina_Casilleros.py:141': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'pagina_Casilleros.py:161': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'pagina_Casilleros.py:215': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'pagina_Casilleros.py:229': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'pagina_Casilleros.py:244': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'pagina_Casilleros.py:249': 'color: #FFFFFF;font-size: 20px; font-weight: bold;',
    'pagina_Casilleros.py:254': 'color: #FFFFFF; margin: 0; padding: 0;font-size: 20px;',
    'pagina_Casilleros.py:258': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'pagina_Casilleros.py:273': 'color: #FFFFFF;font-size: 40px; font-weight: bold;',
    'pagina_Casilleros.py:280': '\n            QTableWidget {\n                background-color: #222126;\n                color: white;\n                border: 1px solid #222126;\n                alternate-background-color: #131216; /* Color de fila alternativa */\n            }\n\n            QTableWidget::item {\n                background-color: #151419; /* Color de fondo de las celdas */\n                border: 0px solid #222126; /* Color y ancho del borde de las celdas */\n            }\n\n            QTableWidget::item:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse sobre una celda */\n            }\n\n            QTableWidget::item:selected {\n                background-color: #3c3b40; /* Color de fondo al seleccionar una celda */\n                color: white; /* Color del texto de la celda seleccionada */\n            }\n\n            QHeaderView::section {\n                background-color: #151419; /* Color de fondo de las cabeceras de las columnas */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n                border: none; /* Sin borde */\n                padding: 4px; /* Ajuste del relleno */\n            }\n\n            QHeaderView::section:hover {\n                background-color: #2a292e; /* Color de fondo al pasar el mouse */\n            }\n\n            QHeaderView::section:selected {\n                background-color: white; /* Color de fondo al seleccionar */\n                color: white; /* Color del texto de las cabeceras de las columnas */\n            }\n\n            QLineEdit {\n                color: white; /* Color del texto del QLineEdit durante la edición */\n            }\n        ',
    'pagina_Casilleros.py:333': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
    'pagina_Casilleros.py:346': 'color: White; background-color: #222125; font-size: 15px; border-radius: 15px; padding: 10px 20px;',
}
